---
## This is really a pretty stupid/simple role, but I'm making it a role in the
##  hopes that it can be reused...

- name: ensure the flatpak package is installed
  package:
    name: flatpak
    state: installed

- name: enable the flatpak repositories
  become: true
  flatpak_remote:
    name: "{{ (item | basename | splitext)[0] }}"
    state: present
    flatpakrepo_url: "{{ item }}"
  with_items: "{{ flatpakrepo_urls }}"
  when: 
    - flatpakrepo_urls is defined
    - flatpakrepo_urls != ""

- name: install flatpaks
  become: true
  flatpak:
    name: "{{ item }}"
    state: present
  with_items: "{{ flatpak_name }}"
  when: 
    - flatpak_name is defined
    - flatpak_name != ""
