---
- name: Converge
  hosts: all
  pre_tasks:
  - name: create test users
    become: true
    user:
      name: '{{ item }}'
      state: present
      home: '/home/{{ item }}'
      createhome: true
    with_items:
      - test_usr1
      - test_usr2
      - test_usr3

  roles:
    - role: ansible-role-flatpak-default-install
      flatpakrepo_urls:
        - https://sdk.gnome.org/gnome-apps.flatpakrepo
        - https://dl.flathub.org/repo/flathub.flatpakrepo
      flatpak_name:
        - org.gnome.clocks
        - org.gnome.gedit
